#!/bin/bash
# vim:set ts=2 sw=2 et:

# ## Create Arch root for building a PKGBUILD
#  # Options:
#  --dev: use development version of pacman,pyalpm,namcap
#  --date=yyyy/mm/dd: use archived archilinux repository.
#  # How it works:
#    * create Arch root in /tmp/root
#    * install `base-devel` packages group in /tmp/root
#    * mount $PWD as /build, write enabled
#    * mount /home/_pacman_cache, as itself, read-only
#    * mount /home/_ccache, as /home/user/.ccache, write enabled
#    * enable X11 applications, mount /tmp/.X11-unix, read-only
#    * add `aur` repository located in `/home/_pacman_cache/aur`
#    * add new user: `user`
#    * add `user` to sudoers and allow executing all commands without password
#    * add `-j8` to MAKEFLAGS
#    * switch compression scheme to zstd
#    * update pacman repository db
#    * install: vim, moreutils, man, git, makepkg-optimize
#    * create `user` home: `/usr/home` and set correct permissions
#    * add `user` password=`user` (need for `sudo` to work)
#    * make source we starts in `/build/$$$` by adding it to `~/.bashrc`
#    * boot and run $@ if provided, otherwise run `bash`


#Cleanups.
  tmp=$(mktemp -d)
  trap 'rm -rf $tmp' EXIT

while true; do
  case "$1" in
    --dev)
      # override stock pacman.with.pacman-git
      _dev_pacman=1
      shift;;
    --date=*)
      _repo_date=${1#*=}
      shift;;
    *)
      break;;
  esac
done

# Test if _repo_date resolve to correct archlinux archive url.
[ -v _repo_date ] && {
  if curl -s https://archive.archlinux.org/repos/"${_repo_date}"/|hq head text|grep -q 404
  then
    echo "Error: --date=${_repo_date} format should be yyyy/mm/dd"
    exit 1
  else
    _mirror_url="https://archive.archlinux.org/repos/${_repo_date}/"
  fi
}

#Define nspawn root path.
nspawn="arch-nspawn /tmp/root"
#Define mount nspawn mount options.
nspawn+=" --bind-ro=/tmp/.X11-unix"
nspawn+=" --bind-ro=/home/_pacman_cache/"
nspawn+=" --bind=/home/_ccache:/home/user/.ccache"
nspawn+=" --bind=$(pwd):/build/$(basename "$PWD")"

#Allow nspawn to start X11 applications.(https://wiki.archlinux.org/index.php/Chroot#Run_graphical_applications_from_chroot)
xhost +local:

#Create root if not already exist.
[ -d /tmp/root ] || {
  #If "$_repo_date" is defined use it as mirror in pacman.conf
  [ -v _mirror_url ] && {
    cp /usr/share/devtools/pacman-extra.conf "$tmp/pacman.conf"
    sed "s|^Include = /etc/pacman.d/mirrorlist$|Server = ${_mirror_url}\$repo/os/\$arch/|g" -i "$tmp/pacman.conf"
    mkarchroot_args="-C $tmp/pacman.conf"
  }
  mkarchroot $mkarchroot_args /tmp/root base-devel
# Installing pacman-git requires reapplying pacman.conf modification.
  $nspawn bash -xec 'echo -e "[aur]\nSigLevel = Optional TrustAll\nServer = file:///home/_pacman_cache/aur" >> /etc/pacman.conf'
  ((_dev_pacman)) && $nspawn bash -xec 'pacman -S --noconfirm --ask=4 pacman-git'
  ((_dev_pacman)) && $nspawn bash -xec 'echo -e "[aur]\nSigLevel = Optional TrustAll\nServer = file:///home/_pacman_cache/aur" >> /etc/pacman.conf'
# Configure chroot
  $nspawn bash -xec 'useradd user'
  $nspawn bash -xec 'echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers'
  $nspawn bash -xec 'echo MAKEFLAGS="-j8" >> /etc/makepkg.conf'
  $nspawn bash -xec 'sed -i "s/tar\.xz/tar\.zst/" /etc/makepkg.conf'
  $nspawn bash -xec 'pacman -Sy'
  $nspawn bash -xec 'pacman -S --noconfirm vim moreutils man git makepkg-optimize'
  ((_dev_pacman)) && $nspawn bash -xec 'pacman -S --noconfirm pyalpm-git aur/namcap'
# Configure user
# $nspawn bash -xec 'mkdir /home/user'
  $nspawn bash -xec 'chown -R user:user /home/user'
  $nspawn bash -xec 'chpasswd <<<"user:user" '
  $nspawn --user=user bash -xvec "echo \"cd /build/$(basename "$PWD")\" >> ~/.bashrc"
}
# Run bash or command form cli
(($#)) && $nspawn --user=user bash -xvec "cd /build/$(basename "$PWD"); $*; bash"
(($#)) || $nspawn --user=user bash

